### ISSUE TITLE
./scripts/gen_cusip_csv.sh error

### ISSUE THREAD

**Issue by aidan-n** [aclindsa/moneygo#1]
When I was setting up the program, I got up to this point:
`$ go generate -v github.com/aclindsa/moneygo`

My terminal got caught in an infinite loop saying

> ./scripts/gen_cusip_csv.sh: line 8: curl: command not found
> ./scripts/gen_cusip_csv.sh: line 13: curl: command not found
> ./scripts/gen_cusip_csv.sh: line 8: curl: command not found
> ./scripts/gen_cusip_csv.sh: line 13: curl: command not found
> ./scripts/gen_cusip_csv.sh: line 8: curl: command not found
> ./scripts/gen_cusip_csv.sh: line 13: curl: command not found

**Comment by aclindsa** [comment]
@aidan-n Try installing the `curl` command on your system.

Note: it isn't actually in an infinite loop, it's just looping over every CUSIP it could find on the SEC's list that it downloaded. If you would like to skip this step entirely, follow the steps in the last paragraph in the 'Installation' section on the README (to touch the cusip_list.csv file).

**Comment by aidan-n** [comment]
So I installed curl. Now when starting over the installation process, this message appears:
```
go get -v github.com/aclindsa/moneygo
can't load package: package github.com/aclindsa/moneygo: 
src/github.com/aclindsa/moneygo/security_templates.go:1:1: expected 'package', found 'EOF'

```

I'd like to install it with everything and not leave out security features, but maybe that's not going to be able to happen.

What disadvantages are there to skipping this stuff?

**Comment by aclindsa** [comment]
I suspect this is an issue due to a incorrectly-generated security_templates.go file from your previous failed run (before you installed curl). If you want to try re-generating everything, try removing security_templates.go and cusip_list.csv, then re-running the `go generate` command (this could take up to a few hours). Otherwise, if you want to re-generate without any of the security templates, remove security_templates.go and ensure cusip_list.csv is present but an empty file, then re-run the `go generate` command.

By leaving out the security templates (second option above), you'll have to manually populate any currency/security information (i.e. the CUSIPs, stock tickers for stocks or ISO4217 codes for currencies). This likely isn't a deal-breaker if you just want to play around - it just makes it more user-friendly to add a new stock ticker or currency.

Sidenote: I'd like to streamline how I generate the security templates, but I'm not sure about the legal ramifications of redistributing this information - so I'm sidestepping the issue for now by requiring everyone who uses my code to fetch it for themselves.

**Comment by aidan-n** [comment]
I'm going to update as I go along, in case it helps someone in the future.

First, I just deleted everything and cloned it again. And I have curl installed.

'pwd' means present working directory. 

So enter: `export GOPATH=[FULLPATH]/moneygo/`
    where [FULLPATH] is a placeholder for the full directory path up to moneygo.

Then enter
`$ go get -v github.com/aclindsa/moneygo`

Then, enter
`$ go generate -v github.com/aclindsa/moneygo`

And at this point I go outside.

**Comment by aclindsa** [comment]
Sorry, I missed that you updated your comment and thought you were still outside waiting!

This latest issue looks like a python3 vs python2 issue to me (and I have only tested with a system using python3 by default). I'll work on a patch to make both work and get you to test it.

Thanks for bearing with me as we work through this. By now I'm sure you can tell that this project hasn't been tested by too many others...

**Comment by aidan-n** [comment]
Haha. Alright I'm interested in testing the patch out. And to confirm, I do have python2 on default, with python3 existing but not default.

**Comment by aclindsa** [comment]
@aidan-n Just pushed commit 1a72568ebdcc6f3ec73257249092fc3963294d99 to fixup gen_security_list.py to work with both python 2 and 3, let me know if that works for you. You should be able to speed up the testing by deleting security_templates.go, but leaving the already-generated cusip_list.csv there, and re-running the `go generate` command.

**Comment by aidan-n** [comment]
I did this to merge my branch with the new one:
```
git fetch origin
 git checkout master
 git merge origin/master
```
Then I tried deleting security_templates.go and leaving cusip_list.csv there, then running the generate command. 

Got: 'can't load package: package github.com/aclindsa/moneygo: 
src/github.com/aclindsa/moneygo/security_templates.go:1:1: expected 'package', found 'EOF''

IDK if I'm going to just completely delete it and clone it again.
'

**Comment by aclindsa** [comment]
Was there another error message earlier in the output than the one you just reported?

If you're worried you messed up the git state, you can do `git reset --hard origin/master`. Re-cloning seems unnecessarily time-intensive since you'll have to completely regenerate cusip_list.csv.

**Comment by aidan-n** [comment]
I ended up recloning it, the generate command is running.

**Comment by aidan-n** [comment]
The generation command has finished after a brief 7 hours.

Running
$ `go install -v github.com/aclindsa/moneygo`
results in:

```
reports/src/github.com/aclindsa/moneygo/accounts_lua.go:4:2: cannot find package "context" in any of:
	/usr/lib/go-1.6/src/context (from $GOROOT)
	/home/user/Desktop/git_repos/moneygo/reports/src/context (from $GOPATH)
user@ubuntu:~/Desktop/git_repos/moneygo$ 
```

**Comment by aclindsa** [comment]
From the error message, it looks like you may only have go 1.6 installed. The 'context' package was moved into the standard library as of go 1.7: https://golang.org/doc/go1.7#context

You'll need to install go >= 1.7

**Comment by aidan-n** [comment]
Okay I installed 1.7

This is what happens now:

```
PATH/moneygo$ go install -v github.com/aclindsa/moneygo
can't load package: package github.com/aclindsa/moneygo: 
../src/github.com/aclindsa/moneygo/security_templates.go:1:1: expected 'package', found 'EOF'
```

**Comment by aclindsa** [comment]
What do you mean when you say that the security_templates.go file exists? Does it begin with something like:
```
package main

var SecurityTemplates = []Security{
...
```

I'm a little confused about the prefix on your path. Why does it begin 'PATH/moneygo/reports/src/...'? If 'PATH' is equal to the $GOPATH, as it is defined in the README, I would expect this path to instead be 'PATH/src/...' (omitting 'moneygo/reports').

I'm guessing here, but it sort of looks like it could be that the $GOPATH environment variable, which determines which directory the `go generate` command uses, may not be the same directory you expect it to be. This could happen if you re-ran the `export GOPATH=`pwd`` command inside a different directory than before (I usually only set $GOPATH once to avoid accidentally doing this, or even add it to .bashrc so I can forget about it).

**Comment by aidan-n** [comment]
'PATH' is equal to the rest of the full path, as in 'user/home/...' and so on.

I just tried running export GOPATH='pwd' in the moneygo folder, and then doing the install command. I also tried from the folder above moneygo.

Doing this in moneygo resulted in:
```
can't load package: package github.com/aclindsa/moneygo: cannot find package "github.com/aclindsa/moneygo" in any of:
	/usr/local/go/src/github.com/aclindsa/moneygo (from $GOROOT)
	/home/user/Desktop/git_repos/moneygo/src/github.com/aclindsa/moneygo (from $GOPATH)
```

Doing this in the folder above moneygo resulted in:
`src/github.com/aclindsa/moneygo/security_templates.go:1:1: expected 'package', found 'EOF'
`

I found security_templates.go and it turns out that file is empty. This explains the error message that occurs when running from the folder above moneygo. So I think I ran the generate command in this folder, above moneygo.

I'm not sure why security_templates.go is empty, if you have any advice how to proceed from here I'd appreciated it. And if you can send me security_templates.go, that would also be really helpful.

Hopefully one day this program will be running on my computer haha.

**Comment by aclindsa** [comment]
For one installation of moneygo, $GOPATH should always remain set to the same path. Sorry if my previous comment was more confusing than it was helpful.

What happens if you do:
```
cd $GOPATH/src/github.com/aclindsa/moneygo
./scripts/gen_security_list.py > security_templates.go
```

This is manually running the step in `go generate` that should be creating security_templates.go. If any errors are printed on stderr, or echoed into security_templates.go, maybe this will help debug your issue.

**Comment by aidan-n** [comment]
It returns this:

`bash: cd: /src/github.com/aclindsa/moneygo: No such file or directory`

**Comment by aclindsa** [comment]
Looks like $GOPATH isn't set. What happens if you set it to whatever it is for your moneygo checkout and try again?

**Comment by aidan-n** [comment]
There are two folders I might have ran the go commands from, so I'll try on both.

Folder1 (the folder above moneygo)
Setting the gopath was fine, and so was `cd $GOPATH/src/github.com/aclindsa/moneygo`

Doing this:
`./scripts/gen_security_list.py > security_templates.go`
resulted in:
```
Traceback (most recent call last):
  File "./scripts/gen_security_list.py", line 5, in <module>
    from urllib import request
ImportError: cannot import name request
```


Folder2: (the folder named moneygo)
Setting the gopath was fine.

`cd $GOPATH/src/github.com/aclindsa/moneygo`
resulted in:
`bash: cd: /home/user/Desktop/git_repos/moneygo/src/github.com/aclindsa/moneygo: No such file or directory`



So the folder above moneygo is the right folder to run these commands from, assuming there is a right folder and I didn't mess something up for that.

**Comment by aclindsa** [comment]
The `ImportError: cannot import name request` error _should_ be fixed by 1a72568ebdcc6f3ec73257249092fc3963294d99 (I tested with python2 and that error went away for me). Can you confirm that the directory you ran that command in (Folder1) contains this commit?

I don't know what to tell you about the non-existence of cusip_list.csv when you ran with python3. Perhaps you were just confused about which directory you were in?

FYI, here is some more information about the GOPATH environment variable: https://golang.org/doc/code.html#GOPATH. I think understanding what it is and how it interacts with the `go ...` commands might help.

**Comment by aidan-n** [comment]
I must not have that commit.

I'm definitely confused on which directory I'm supposed to run each command in, and could have messed something up with that.

**Comment by aclindsa** [comment]
Here's what I would do if I were you:
1. Save off cusip_list.csv to somewhere safe (from whichever src/github.com/aclindsa/moneygo directory contains a copy with around 7000 lines)
2. Delete all the copies of moneygo you have checked out.
3. Set $GOPATH to whichever directory you intend to be the go workspace for this moneygo install. You could even put this in your .bashrc to make sure it's always the same in the future.
4. With that set, run `go get -v github.com/aclindsa/moneygo`
5. Copy the cusip_list.csv file you saved off into the newly-created $GOPATH/src/github.com/aclindsa/moneygo directory
6. Finish by running `go generate -v github.com/aclindsa/moneygo` and finally `go install -v github.com/aclindsa/moneygo`

**Comment by aidan-n** [comment]
It worked.

I can open moneygo on port 8080.

I want to have an account, to explore. I wasn't able to log in after making one though.
