### ISSUE TITLE
Can't sign in on fresh install.

### ISSUE THREAD

**Issue by nathanielc** [aclindsa/moneygo#33]
I am getting this error `Error 1: Not Signed In` after first starting the app.

Repro Steps:

1. Start fresh install.
2. Create user admin/admin
3. Login as admin/admin
4. Get the `not signed in` error.

Thanks for putting this together I am excited to try the OFX support. Just need to get it working first.

**Comment by aclindsa** [comment]
I think I tracked it down - it looks like this is a case of my code being more secure than my example instructions. My backend sets cookies to be secure, which doesn't play well with non-HTTPS setups. Try this branch: https://github.com/aclindsa/moneygo/tree/insecure_cookies, or just cherry-pick this commit: https://github.com/aclindsa/moneygo/commit/3f28e083e7e5de54475f52bcb38c7495ecc608a0 and let me know if that works better for you.

**Comment by aclindsa** [comment]
Also, just to warn you - the most frustrating part of getting OFX working is frequently tracking down the right settings for your bank. If you are having trouble getting that to work, open another issue for that and we can look into it.

**Comment by nathanielc** [comment]
@aclindsa Yep, that was the issue. Thanks! I'll let you know how it goes.

**Comment by nathanielc** [comment]
I got one OFX account working :). Thanks again.

**Comment by aclindsa** [comment]
@nathanielc I've now created https://github.com/aclindsa/moneygo/pull/34, which fixes the issue more permanently/securely by always serving over HTTPS instead of allowing insecure cookies. I've tested it and it works for me, but if you have a chance to try it out, let me know how it goes.
